modLoader="javafml" #mandatory
loaderVersion="[1,)" #mandatory
license="MIT License https://github.com/BuiltBrokenModding/AI-Improvements/blob/1.21/LICENSE"
issueTrackerURL="https://github.com/BuiltBrokenModding/AI-Improvements/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/ai-improvements"
authors="BuiltBrokenModding"

[[mods]] #mandatory
modId="aiimprovements" #mandatory
version="${file.jarVersion}" #mandatory
displayName="AI-Improvements" #mandatory
description='''Small adjustments and improvements to AI logic focusing on optimizations for increased server performance''' #mandatory

[[dependencies.aiimprovements]]
    modId="neoforge"
    type="required"
    versionRange="[21,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.aiimprovements]]
    modId="minecraft"
    type="required"
    versionRange="[1.21,1.22)"
    ordering="NONE"
    side="BOTH"